# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\桌面\项目\英特尔杯电赛\比赛后续\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"黑体\";\n"
"background-color: rgb(245, 245, 245);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.widget_2.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-radius:15px")
        self.widget_2.setObjectName("widget_2")
        self.labelimg1 = QtWidgets.QLabel(self.widget_2)
        self.labelimg1.setGeometry(QtCore.QRect(60, 60, 1280*0.7, 720*0.7))
        self.labelimg1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelimg1.setText("")
        self.labelimg1.setObjectName("labelimg1")
        self.labelimg2 = QtWidgets.QLabel(self.widget_2)
        self.labelimg2.setGeometry(QtCore.QRect(964, 60, 1280*0.7, 720*0.7))
        self.labelimg2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelimg2.setText("")
        self.labelimg2.setObjectName("labelimg2")
        #self.pushButton4 = QtWidgets.QPushButton(self.widget_2)
        #self.pushButton4.setGeometry(QtCore.QRect(1500, 800, 170, 60))
        #self.pushButton4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        #self.pushButton4.setStyleSheet("QPushButton{color: rgb(0, 0, 0);\n"
#"background-color: rgb(225, 225, 225);\n"
#"border-color: rgb(245, 245, 245);\n"
#"border: 2px solid white;\n"
#"border-radius:10px;}\n"
#"QPushButton::pressed{background-color :rgb(30, 207, 158)}    \n"
#"")
        #self.pushButton4.setObjectName("pushButton4")
        self.pushButton2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton2.setGeometry(QtCore.QRect(1500, 640, 170, 60))
        self.pushButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2.setStyleSheet("QPushButton{color: rgb(0, 0, 0);\n"
"background-color: rgb(225, 225, 225);\n"
"border-color: rgb(245, 245, 245);\n"
"border: 2px solid white;\n"
"border-radius:10px;}\n"
"QPushButton::pressed{background-color :rgb(30, 207, 158)}    \n"
"")
        self.pushButton2.setObjectName("pushButton2")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setGeometry(QtCore.QRect(60, 600, 1280*0.7,360 ))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton1 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton1.setGeometry(QtCore.QRect(1200, 640, 170, 60))
        self.pushButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1.setStyleSheet("QPushButton{color: rgb(0, 0, 0);\n"
"background-color: rgb(225, 225, 225);\n"
"border-color: rgb(245, 245, 245);\n"
"border: 2px solid white;\n"
"border-radius:10px;}\n"
"QPushButton::pressed{background-color :rgb(30, 207, 158)}    \n"
"")
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton3.setGeometry(QtCore.QRect(1350, 800, 170, 60))
        self.pushButton3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3.setStyleSheet("QPushButton{color: rgb(0, 0, 0);\n"
"background-color: rgb(225, 225, 225);\n"
"border-color: rgb(245, 245, 245);\n"
"border: 2px solid white;\n"
"border-radius:10px;}\n"
"QPushButton::pressed{background-color :rgb(30, 207, 158)}    \n"
"")
        self.pushButton3.setObjectName("pushButton3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(1443, 30, 51, 31))
        self.label_2.setStyleSheet("font: 20pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(890, 0, 261*0.7, 71*0.7))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 20pt \"黑体\";")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(483, 30, 61, 31))
        self.label_6.setStyleSheet("font: 20pt \"黑体\";")
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(483, 570, 101, 31))
        self.label_3.setStyleSheet("font: 20pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.selectimg = QtWidgets.QAction(MainWindow)
        self.selectimg.setCheckable(False)
        self.selectimg.setChecked(False)
        self.selectimg.setEnabled(True)
        self.selectimg.setObjectName("selectimg")
        self.roadGcode = QtWidgets.QAction(MainWindow)
        self.roadGcode.setObjectName("roadGcode")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Object Detection"))
        #self.pushButton4.setText(_translate("MainWindow", "空闲"))
        self.pushButton2.setText(_translate("MainWindow", "开始识别"))
        self.pushButton1.setText(_translate("MainWindow", "开启相机"))
        self.pushButton3.setText(_translate("MainWindow", "当前状态：空闲"))
        self.label_2.setText(_translate("MainWindow", "dst"))
        self.label_4.setText(_translate("MainWindow", "目标识别"))
        self.label_6.setText(_translate("MainWindow", "src"))
        self.label_3.setText(_translate("MainWindow", "result"))
        self.selectimg.setText(_translate("MainWindow", "选择图片"))
        self.roadGcode.setText(_translate("MainWindow", "读取G代码文件"))
